### ISSUE TITLE
Some errors: The type or namespace name ... does not exist in the namespace `OpenCVForUnity'

### ISSUE THREAD

**Issue by huihut** [EnoxSoftware/CVVTuberExample#2]
Hi, I have imported `CVVTuberExample`, `OpenCVForUnity` and `DlibFaceLandmarkDetector`, but there are some errors. Is it caused by the wrong version of opencv or dlib? How to solve it?

![image](https://user-images.githubusercontent.com/23519480/50811946-ac8e6980-134b-11e9-95b8-16c006faa080.png)

![image](https://user-images.githubusercontent.com/23519480/50811917-941e4f00-134b-11e9-9003-a0faf474a01b.png)

```
Assets/CVVTuberExample/CVVTuber/Scripts/Core/MatSourceGetter.cs(4,22): error CS0234: The type or namespace name `CoreModule' does not exist in the namespace `OpenCVForUnity'. Are you missing an assembly reference?
Assets/CVVTuberExample/CVVTuber/Scripts/Core/MatSourceGetter.cs(10,24): error CS0246: The type or namespace name `Mat' could not be found. Are you missing `OpenCVForUnity' using directive?
```

**Comment by EnoxSoftware** [comment]
Thank you for your inquiry.

OpenCV for Unity v2.3.3 is in pending review status.
I asked Unity Support about the review. I got a reply that the Asset Review
Team is now in the holiday season so it will take some more time to finish
the review.

Until OpenCVForUnity 2.3.3 is published in AssetStore, you can download
examples of older versions from the following DL link.


DlibFaceLandmarkDetector_v1.2.5_to_v1.2.4_Patch.unitypackage
https://www.dropbox.com/s/s4ggi4ps4...ctor_v1.2.5_to_v1.2.4_Patch.unitypackage?dl=0
By importing this unitypackage you can downgrade DlibFaceLandmarkDetector v1.2.5 to DlibFaceLandmarkDetector v1.2.4. Please import DlibFaceLandmarkDetector v1.2.5 from AssetStore and then import this patch. FaceSwapperExample 1.0.7, FaceMaskExample 1.0.6 and CVVTuberExample 1.0.1 require DlibFaceLandmarkDetector 1.2.4.


CVVTuberExample1.0.1
https://www.dropbox.com/s/tccnr216bwq1xiq/CVVTuberExample1.0.1.unitypackage?dl=0

DlibFaceLandmarkDetectorPlayMakerActions1.0.2
https://www.dropbox.com/s/jkwsk6c2p...tectorPlayMakerActions1.0.2.unitypackage?dl=0

OpenCVForUnityPlayMakerActions1.0.5
https://www.dropbox.com/s/x4xo907pnda7chh/OpenCVForUnityPlayMakerActions1.0.5.unitypackage?dl=0

FaceMaskExample1.0.6
https://www.dropbox.com/s/aly2gtf5vmji6x6/FaceMaskExample1.0.6.unitypackage?dl=0

FaceSwapperExample1.0.7
https://www.dropbox.com/s/6gwa0v8eunqjnv5/FaceSwapperExample1.0.7.unitypackage?dl=0

FaceTrackerExample1.1.8
https://www.dropbox.com/s/u2cx1nlkddz8lnn/FaceTrackerExample1.1.8.unitypackage?dl=0

MarkerBasedARExample1.2.1
https://www.dropbox.com/s/u2rfto39ohu18ja/MarkerBasedARExample1.2.1.unitypackage?dl=0

MarkerLessARExample1.0.4
https://www.dropbox.com/s/rpovz53y3hhhlgj/MarkerLessARExample1.0.4.unitypackage?dl=0

RealTimeFaceRecognitionExample1.0.4
https://www.dropbox.com/s/rjot3qaih580xyp/RealTimeFaceRecognitionExample1.0.4.unitypackage?dl=0


Regerds,
EnoxSoftware

2019年1月8日(火) 14:53 Menghui Xie <notifications@github.com>:

**Comment by huihut** [comment]
Thank you. I can run CVVTuberExample 1.0.1
