### ISSUE TITLE
failed to load sp_human_face_68.data

### ISSUE THREAD

**Issue by asonee** [EnoxSoftware/CVVTuberExample#4]

**Comment by EnoxSoftware** [comment]
You may not have completed the setup procedure.
Please move the “DlibFaceLandmarkDetector/StreamingAssets/sp_human_face_68.dat” to the “Assets/StreamingAssets/” folder.
![image](https://user-images.githubusercontent.com/7920392/104926677-d02d2580-59e3-11eb-91ec-1f4eec1959ee.png)

**Comment by asonee** [comment]
thanks for your replay!  my model path has none-ascii char lead to this issue.
